# Homelab Media Stack - Terraform Root Module
#
# This module orchestrates both UniFi DNS and Cloudflare Tunnel modules
# to deploy a complete homelab media stack infrastructure.
#
# Workflow:
#   1. Read KCL-generated JSON configuration files
#   2. Configure UniFi and Cloudflare providers
#   3. Instantiate modules with parsed configuration
#   4. Output deployment information

# ============================================================================
# LOCAL VALUES
# ============================================================================

locals {
  # Construct full paths to KCL-generated JSON files
  unifi_json_path      = "${var.generated_files_path}/unifi.json"
  cloudflare_json_path = "${var.generated_files_path}/cloudflare.json"

  # Read and parse the JSON configuration files
  # These files are generated by running `kcl run main.k` in the parent directory
  unifi_config      = jsondecode(file(local.unifi_json_path))
  cloudflare_config = jsondecode(file(local.cloudflare_json_path))
}

# ============================================================================
# PROVIDER CONFIGURATION
# ============================================================================

# UniFi Provider
# Manages DNS records and queries device information from UniFi Controller
provider "unifi" {
  username = var.unifi_username
  password = var.unifi_password
  api_url  = "https://${var.unifi_controller_host}"
  # Skip TLS verification for self-signed certificates (common in homelab setups)
  # Set to false if using valid certificates
  allow_insecure = true
}

# Cloudflare Provider
# Manages Cloudflare Tunnels and DNS records
provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

# ============================================================================
# MODULE: UNIFI DNS
# ============================================================================

module "unifi_dns" {
  source = "../../../terraform/modules/unifi-dns"

  # Pass the parsed UniFi configuration from KCL-generated JSON
  config = local.unifi_config

  # If strict mode is enabled, the module will fail on missing MAC addresses
  # If disabled, missing devices are tracked in outputs for review
  strict_mode = var.unifi_strict_mode
}

# ============================================================================
# MODULE: CLOUDFLARE TUNNEL
# ============================================================================

module "cloudflare_tunnel" {
  source = "../../../terraform/modules/cloudflare-tunnel"

  # Pass the parsed Cloudflare configuration from KCL-generated JSON
  config = local.cloudflare_config
}

# ============================================================================
# NOTES
# ============================================================================
#
# DEPENDENCY ORDER:
#   The modules are independent and can be applied in any order.
#   However, recommended order for first-time setup:
#     1. UniFi DNS (creates internal DNS records)
#     2. Cloudflare Tunnel (creates tunnels and external DNS)
#
# CLOUDFLARED SETUP:
#   After applying, you must:
#     1. Retrieve tunnel tokens from outputs
#     2. Install cloudflared on your media server
#     3. Configure cloudflared with the tunnel credentials
#     4. Start the cloudflared service
#
# See README.md for detailed cloudflared setup instructions.
